- name: Copy folder to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: radholm
          remote: /var/www/
          rmRemote: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
